### ISSUE TITLE
Plugins getting TypeError after update to AutoGPT 0.3.1

### ISSUE THREAD

**Issue by Monty1122** [Significant-Gravitas/Auto-GPT-Plugins#184] opened 2023-05-28 12:49 UTC
was working with 0.2.2 - updated to 0.3.1 and now getting errors in loading all plugins - did the plugin reinstall - but same issue - any body seeing this - sample from running AutoGPTEmailPlugin - but seems to be the same for all for me

Traceback (most recent call last):
  File "/Users/david/opt/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/david/opt/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/david/Desktop/dkautogpt/Auto-GPT-latest/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/david/Desktop/dkautogpt/Auto-GPT-latest/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/Users/david/Desktop/dkautogpt/Auto-GPT-latest/autogpt/main.py", line 127, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "/Users/david/Desktop/dkautogpt/Auto-GPT-latest/autogpt/plugins.py", line 238, in scan_plugins
    loaded_plugins.append(a_module())
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/abstract_singleton/__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
TypeError: Can't instantiate abstract class AutoGPTEmailPlugin with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input

same for AutoGPTApiTools 
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/abstract_singleton/__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
TypeError: Can't instantiate abstract class AutoGPTApiTools with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input

**Comment by Lrennard** [comment] 2023-05-29 08:02
Have you tried:

pip install -r requirement.txt

python -m install-pluing-deps

**Comment by dynamikapps** [comment] 2023-05-29 15:55
It was working fine for me but after the update, I'm getting the same error "...TypeError: Can't instantiate abstract class AutoGPTApiTools with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input." I reinstalled the plugins but no go. Any ideas?

**Comment by Lrennard** [comment] 2023-05-29 20:36
"I reinstalled the plugins but no go." Did you pull latest plugin folder from repo?

"Can't instantiate abstract class AutoGPTApiTools" Definitely a python issue, it's hard to tell without knowing more about your configuration but my general recommendation would be

Make sure you have the latest version of the Plugin repo
Make sure you are running the AGPT stable branch
after downloading plugin folder install dependencies <--install-plugin-deps>

**Comment by suibber** [comment] 2023-05-30 02:48
getting the same error. 

I executed ```./run.sh --install-plugin-deps``` and everything is fine

"TypeError: Can't instantiate abstract class AutoGPTApiTools with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input"

**Comment by Siivers** [comment] 2023-05-30 20:24
Might be related to this being merged into master?
https://github.com/Significant-Gravitas/Auto-GPT/pull/4402/files

**Comment by Monty1122** [comment] 2023-05-30 20:37
@Siivers I updated to the latest master - now on ##4482 - but I still get this 

  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/abstract_singleton/__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
TypeError: Can't instantiate abstract class AutoGPTEmailPlugin with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input

I also reinstalled the plugins code

**Comment by nospoon** [comment] 2023-05-31 10:18
The stable branch is also affected. Can't get any plugins working anymore.

**Comment by nospoon** [comment] 2023-05-31 10:23
It also happens on the stable branch which was last updated 2 weeks ago, so the issue is most likely with the plugins repository, not Auto-GPT itself.

**Comment by stefan-durina** [comment] 2023-06-01 17:49
I have the same issue, fresh install according to the manual 

File "C:\Users\sd\AppData\Local\Programs\Python\Python311\Lib\site-packages\abstract_singleton\__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class AutoGPTApiTools with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input

**Closed** 2023-06-01 23:14 UTC
Labels: bug

**Comment by ntindle** [comment] 2023-06-07 13:52
Did you use the latest versions of the plugins?

**Comment by derudra** [comment] 2023-06-07 15:06
Yes i Did. It was a fresh install of the latest stable release  of AutoGPT and installed the official plugins latest also.

**Comment by Stui** [comment] 2023-06-09 09:46
Yup same here! Tried reinstalling everything from a scratch but problem still persists.
