### ISSUE TITLE
Open assistant plugin?

### ISSUE THREAD

**Issue by dustinwloring1988** [Significant-Gravitas/Auto-GPT-Plugins#142] opened 2023-05-12 04:19 UTC
Perhaps a plugin that calls the inference script directly from a self hosted instants. This would be usefully for testing or just playing around with autogpt and don't wanna have to pay openai.

Here is the project link: https://github.com/LAION-AI/Open-Assistant

**Comment by ntindle** [comment] 2023-05-14 22:20
duplicate of #38

**Closed by ntindle** 2023-05-14 22:20 UTC
Labels: request for plugin
